package Simuladorpokemon;

public class Batalha {
    
    
    private Integer meuPokemonHP;
    private Integer outroPokemonHP;
    private String meuPokemonNome;
    private String outroPokemonNome;
   

    
    public Integer getMeuPokemonHP() {
        return meuPokemonHP;
    }
    public void setMeuPokemonHP(Integer meuPokemonHP) {
        this.meuPokemonHP = meuPokemonHP;
    }

   
    
    
    public Integer getOutroPokemonHP() {
        return outroPokemonHP;
    }
    public void setOutroPokemonHP(Integer outroPokemonHP) {
        this.outroPokemonHP = outroPokemonHP;
    }

    
    
    public String getMeuPokemonNome() {
        return meuPokemonNome;
    }
    public void setMeuPokemonNome(String meuPokemonNome) {
        this.meuPokemonNome = meuPokemonNome;
    }

   
    
    public String getOutroPokemonNome() {
        return outroPokemonNome;
    }
    public void setOutroPokemonNome(String outroPokemonNome) {
        this.outroPokemonNome = outroPokemonNome;
    }
    
}

